#!/usr/bin/env bash
# script to install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
if [[ ! $(pgrep nginx) ]]; then
    sudo service nginx start
fi
sudo ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '\n\t link ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4' /etc/nginx/sites-available/default
sudo service nginx restart
echo -e "\nfinish runging\n"