#!/usr/bin/env bash
# script to install nginx
sudo apt-get update -y -qq
sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
text="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$text/" /etc/nginx/sites-enabled/default
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart