#!/usr/bin/env bash
# Install load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 490162-web-01 100.25.3.60:80 check
        server 490162-web-02 100.26.157.67:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
