#!/usr/bin/env bash
#Displays FizzBuzz when the number is a multiple of 3 and 5

i=1

while [ $i -le 101 ]
do
	if (( i % 15 == 0 )); then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
	else
		echo $i
	fi
	(( i = i + 1 )) || true
done