#!/usr/bin/env bash
#Tell the story of passwd

while IFS=: read -r usr password uid gid usernamee homedirectory loginn
do
	echo "The user $usr is part of the $gid gang, lives in $homedirectory and rides $loginn. $uid's place is protected by the passcode $password, more info about the user here: $usernamee"
done </etc/passwd