#!/usr/bin/env bash
# Change your home IP
cp /etc/hosts ~/hosts.temp
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.temp
sed -i 's/.*facebook.com//g' ~/hosts.temp
sed -i '1 a 8.8.8.8 facebook.com' ~/hosts.temp
echo "8.8.8.8		facebook.com" >> ~/hosts.temp
cp -f ~/hosts.temp /etc/hosts